### ISSUE TITLE
Create a Lang module

### ISSUE THREAD

**Issue by ghost** [ocaml/v3.ocaml.org-rescript#333]
We will need to tag data with the language its written in. We will also need to dispatch logic basic on an indicated language value. Let's be prepared for those scenarios by introducing a `Lang` module which has constants for the current set of languages that ocaml.org supports. 

We will mostly likely use `react-intl` when implementing internationalization support, so considering imitating how it defines constants: https://github.com/formatjs/formatjs.

**Comment by rdavison** [comment]
Correct me if I'm wrong but as it stands it seems to me that this issue is asking for a module that looks like:
```rescript
type t = [
  | `En
  | `Fr
  | ...
]
```

Am I mistaken?  If not, would it make more sense to just use `react-intl` or finding a binding to it, and using it instead of defining what appears to me as an exceedingly simple module?

**Comment by agarwal** [comment]
>  it seems to me that this issue is asking for a module that looks like

Yes, that's it. It is a very simple module. I wanted the type to exist, so that future harder work will be structured around this. Since it is so simple, you could go ahead with some refactoring related to this. Search for values with names like `*En`, and convert these to functions that take a `Lang.t`.

**Comment by ghost** [comment]
The issue will feed into the overall work in #145.

**Comment by ghost** [comment]
I consider this issue complete.

**Comment by ghost** [comment]
Review of #438:

Please update MainLayout and GlobalData modules to use the Lang type.

**Comment by rdavison** [comment]
> Review of #438:
> 
> Please update MainLayout and GlobalData modules to use the Lang type.

Merged https://github.com/ocaml/v3.ocaml.org/pull/540
