### ISSUE TITLE
New page: Academic Excellence

### ISSUE THREAD

**Issue by jonludlam** [ocaml/v3.ocaml.org-rescript#370]
Implement the Academic Excellence page, as show in this design: https://www.figma.com/file/36JnfpPe1Qoc8PaJq8mGMd/V1-Pages-Next-Step?node-id=1774%3A40.

![image](https://user-images.githubusercontent.com/1385802/119174233-527f3200-ba36-11eb-8f7b-757402f7bc15.png)

**Comment by shreyaswikriti** [comment]
Hello, I would like to work on this. Can you provide some more detail?

**Comment by patricoferris** [comment]
Hi @shreyaswikriti -- you can definitely work on this. Currently we don't actually have the data so that would be a good first step, then we can create the page. Unlike the original ocaml.org we are structuring the data rather than just having it baked into a markdown file in HTML. 

For the data, you will want to fork and PR the information to [ocaml/ood](https://github.com/ocaml/ood). Ood is our "database". I suspect this can take a very similar format to the [books](https://github.com/ocaml/ood/tree/main/data/books) in that each entry of "academic excellence" can be a markdown file with some information as markdown and the rest as yaml. I will create an issue on over there and tag. Does this sound good? 

EDIT: data issue https://github.com/ocaml/ood/issues/24

**Comment by shreyaswikriti** [comment]
OK, I'll start working on this.

**Comment by ghost** [comment]
If someone is actively working on this issue, they should start by creating an empty page which this issue is requesting: #417.

**Comment by ghost** [comment]
This may be useful when implementing this page: https://nextjs.org/docs/routing/dynamic-routes.

**Comment by ghost** [comment]
This looks promising for the map: https://react-leaflet.js.org/docs/start-introduction.
