### ISSUE TITLE
Simple i18n redirects

### ISSUE THREAD

**Issue by rdavison** [ocaml/v3.ocaml.org-rescript#477]
When a user navigates to a page which doesn't exist, the first thing we should try to do is redirect them to the English language version of the site.  If the English language version doesn't exist, then they should see the 404 page.

**Comment by ghost** [comment]
Review of PR #478:

When I visit "/badpage", it redirects me to "/en" instead of presenting "not found." I think the case when the first segment isn't a language prefix (the length of the string is greater than two) should treat the first segment as a page name. In this case, I would redirect to "/en/badpage" and then allow that to redirect to "not found."

**Comment by ghost** [comment]
The last subtle issue isn't important and not very likely to be encountered by a real user.
